services:
  app:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=/api
    container_name: todo-frontend

  server:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    environment:
      REDIS_URL: redis://redis:6379
      MONGO_URL: mongodb://root:example@mongo:27017/the_database?authSource=admin
    container_name: todo-backend
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo_prod_data:/data/db
  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis_prod_data:/data


  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse_proxy
    depends_on:
      - app
      - server

volumes:
  mongo_prod_data:
  redis_prod_data:
